### ISSUE TITLE
Melhorias no readme

### ISSUE THREAD

**Issue by thuram** [Lorenalgm/DevChallenge#1]
Boa noite, gostei muito do projeto e gostaria de contribuir. 

Mas fiquei com algumas dúvidas sobre como iniciar o projeto na minha máquina, acredito que colocar as informações sobre o backend e quais comandos devem ser executados podem ajudar bastante.

**Comment by Lorenalgm** [comment]
Oi, Lucas! Ahh que massa!

Só te adiantando, vou deixar aqui o repositório do backend: https://github.com/Lorenalgm/DevChallengeAPI

Vou adicionar ainda hoje como executar o projeto lá no readme, beleza? Valeu pelo feedback :)

**Comment by thuram** [comment]
Show, essa semana ainda vou dar uma olhada no projeto para te ajudar :)

**Comment by Lorenalgm** [comment]
Fechou! Acabei de atualizar o readme com os passos para o setup. Qualquer dúvida me avisa!
