### ISSUE TITLE
Ranking de contribuições

### ISSUE THREAD

**Issue by Lorenalgm** [Lorenalgm/DevChallenge#10]
Todos os devs ficam registrados no schema do MongoDB, então pensei em fazer um ranking com devs que mais contribuíram com desafios. O que acham?

Até então já deixei disponível no site a aba com os desenvolvedores, listando suas informações e contatos.

Se alguém tiver interesse em implementar, pode ficar à vontade! Ainda não montei nenhum layout disso, aberta à sugestões :)

**Comment by Lorenalgm** [comment]
@[ViniciusCastroJS](https://github.com/ViniciusCastroJS) que também tava pensando na ideia, depois dá tuas considerações aqui! haha

**Comment by mmouradev** [comment]
Acho mais bacana esperar pelo sistema de login e fazer ranking com um estilo de gamification, na pegada do que a DevMedia vem adotando.

Ranking de colaborações, ranking de desafios realizados, etc..

**Comment by Lorenalgm** [comment]
Show! Vou fazer futuramente o/

**Comment by Lorenalgm** [comment]
Ranking já em construção na issue #51!
