### ISSUE TITLE
Sugestões de correções CSS

### ISSUE THREAD

**Issue by Hilverton** [Lorenalgm/DevChallenge#25]
<img src="https://user-images.githubusercontent.com/44450158/88850789-38801480-d1c2-11ea-8f16-b6da47aab600.jpeg" heigth="40%" width="40%">
1. Sugestão da divisão das tecnologias em labels separadas. E ainda tem o ajuste do botão que fica por trás do slide.
<img src="https://user-images.githubusercontent.com/44450158/88850964-77ae6580-d1c2-11ea-9f66-5949db02893e.jpeg" heigth="40%" width="40%">
2. Responsivo ficará assim.

3. Fiz o alinhamento do skeleton responsivo.

4. Ainda não implementado: o componente Header está sendo usado em todas as páginas, uma forma de resolver isso é colocando o Header nas rotas, antes do Switcher, e assim aparecerá em todas as rotas.

Posso mandar a PR @Lorenalgm? Os demias tem algum ponto a comentar?

**Comment by magdielndantas** [comment]
É uma boa ideia, @Hilverton! Também fiz algumas sugestões no mesmo sentido através de um arquivo no Figma. Vou te enviar por meio do Discord para que você confira e pensemos na possibilidade de fazermos juntos.

**Comment by Hilverton** [comment]
Resolvido!
