### ISSUE TITLE
CSS das labels está bugado

### ISSUE THREAD

**Issue by Cristuker** [Lorenalgm/DevChallenge#3]
![Screenshot from 2020-05-26 10-10-44](https://user-images.githubusercontent.com/42705870/82904744-4357c800-9f39-11ea-9c21-d7d12c00cf2d.png)

**Comment by Lorenalgm** [comment]
Valeu, Cristian! Na verdade faltou o css deles mesmo haha Vou adicionar :)

**Comment by Lorenalgm** [comment]
CSS corrigido!

![image](https://user-images.githubusercontent.com/19291466/83210703-ebd07c80-a131-11ea-9063-c96026941d1c.png)
