### ISSUE TITLE
feat(frontend): Add i18n to the website

### ISSUE THREAD

**Issue by esau-morais** [Lorenalgm/DevChallenge#35]
![react-i18next](https://miro.medium.com/max/800/1*_kq6WxcMN9G_IiLnP0Jq_g.png)

### Expected

More languages (English, Spanish, at least)

### Actual

Just portuguese

### What is i18n?

Internationalization (i18n) is the process of preparing software so that it can support local languages and cultural settings. ... I18n is product development focused so that in the case of software, one code base is made capable of supporting worldwide languages and locale-specific formatting and behaviors

### Why you should add i18n feature

Open-source supporting → I think this is enough to explain how important it is.

### Steps
- [ ] Install [react-i18next](https://react.i18next.com/) library
- [ ] Make the translations
     - [ ] English (United States)
     - [ ] Portuguese (Brazil)

**Comment by pedrohram** [comment]
Thanks for your suggestion, Esau!

Could you solve this issue with a Pull Request? Do you have time and knows how to begin with?

**Comment by esau-morais** [comment]
> Thanks for your suggestion, Esau!
> 
> Could you solve this issue with a Pull Request? Do you have time and knows how to begin with?

Yes, how I explained in the community, the issue is just a validation to the pull request. I need the community participation to continue. 

Regards,
Esaú

**Comment by pedrohram** [comment]
> > Thanks for your suggestion, Esau!
> > Could you solve this issue with a Pull Request? Do you have time and knows how to begin with?
> 
> Yes, how I explained in the community, the issue is just a validation to the pull request. I need the community participation to continue.
> 
> Regards,
> Esaú

Feel free to contribute! I will open a Project board here.

The data is also stored in Brazilian Portuguese. Do you have any idea of how workaround this without flood the database?

**Comment by esau-morais** [comment]
Thank you! 

Yes, I just need to analyse the project before

**Comment by stevescruz** [comment]
I agree this issue, I planned to talk about this in the meeting saturday. I am interested in learning to  implement this. I can also translate PT-BR to English and Spanish.

**Comment by esau-morais** [comment]
> I agree this issue, I planned to talk about this in the meeting saturday. I am interested in learning to implement this. I can also translate PT-BR to English and Spanish.

Good to know. The translations is the hard part, we need to review well

**Comment by pedrohram** [comment]
We have an API Reference available in the other repo that's filled with request and response examples.

I highly recommend that you give a look.

Follow the link: https://github.com/Lorenalgm/DevChallengeAPI/blob/master/REFERENCE.md

**Comment by stevescruz** [comment]
By the way another thing we should decide upon is to define a more strict language policy for commits and issues to standardize it. But this is off-topic.

**Comment by pedrohram** [comment]
@stevescruz Please see: https://github.com/Lorenalgm/DevChallengeAPI/tree/master/.github

**Comment by esau-morais** [comment]
We can continue this discussion in the community: it's not a good practice use issue's section to decide
