### ISSUE TITLE
fix(docs): Add different translations to README

### ISSUE THREAD

**Issue by esau-morais** [Lorenalgm/DevChallenge#36]
### Expected

Different README's, differente languages (English and Spanish, at least)

### Actual 

One README, two languages (incomplete)

### Upcoming 

- [X] English translation
- [x] Spanish translation
- [x] More translations

### Folder Structure

```
DevChallenge
|
|
└───.github/ISSUE_TEMPLATE
|
|
└───frontend
│   
|
└───translations
|         |
|         |  README.language.md (language must be changed by the language abbreviation)
|
|  README.md (Main language)
```

-----

[Template](https://github.com/firstcontributions/first-contributions)

**Comment by GuillaumeFalourd** [comment]
I can help with a *french* translation.
How should I proceed ? Creating A README-FR.md file ?

**Comment by esau-morais** [comment]
> I can help with a _french_ translation @esau-morais and @pedrohram.
> How should I proceed ? Creating A README-FR.md file ?

Thank you! Follow these steps:

- [ ] Fork this repository and clone

![Forking](https://camo.githubusercontent.com/6f03010c651d060f8b7cfc17da7098c1757c4ead/68747470733a2f2f6669727374636f6e747269627574696f6e732e6769746875622e696f2f6173736574732f526561646d652f666f726b2e706e67)

`git clone github.com/user/DevChallenge.git`

- [ ] Use the branch called `translations`
- [ ] Create a file called `README.fr.md`
- [ ] Edit the `README.md` adding the french language icon

<kbd>[<img title="French" alt="French" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/fr.svg" width="22">](./translations/README.fr.md)</kbd>

`<kbd>[<img title="French" alt="French" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/fr.svg" width="22">](./translations/README.fr.md)</kbd>`

- [ ] Edit the `translations/README.md` adding the french language icon/link

|                                                                                                                                                                                                                                                                             |Link                                                       |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| <img alt="French" title="French" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/fr.svg" width="22">                                                                                                                                                 | Français                                               |

```
| <img alt="French" title="French" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/fr.svg" width="22">                                                                                                                                                 | Français                                               |
```

**Comment by natastro** [comment]
Happy to help with Spanish translations if needed!

**Comment by stevescruz** [comment]
@natastro that would be great

**Comment by NickCwh** [comment]
Happy to help with Japanese or Chinese translations if needed!

**Comment by esau-morais** [comment]
> Happy to help with Japanese or Chinese translations if needed!

Go ahead!! 

_Note: Don't forget to follow the [template](https://github.com/Lorenalgm/DevChallenge/issues/36#issuecomment-703087591)_

**Comment by fabriciocunhauk** [comment]
Posse fazer a tradução para inglês?

**Comment by esau-morais** [comment]
> Posso fazer a tradução para o inglês?

Obrigado, mas já há uma tradução da documentação para o Inglês
