### ISSUE TITLE
Criar tela de Ranking (Create Ranking screen)

### ISSUE THREAD

**Issue by IncognitaDev** [Lorenalgm/DevChallenge#51]
Criar estrutura da tela de Ranking
Design disponível em: https://www.figma.com/file/xpVBgW6AQqCRXDxLmJTggX/DevChallenge?node-id=0%3A1

Create structure of ranking view
Design : https://www.figma.com/file/xpVBgW6AQqCRXDxLmJTggX/DevChallenge?node-id=0%3A1

**Comment by matheusdoedev** [comment]
Olá, bom dia. De onde partiria o link para essa page? fiquei com essa dúvida. Posso pegar essa issue ?

**Comment by IncognitaDev** [comment]
> Olá, bom dia, tudo bem? De onde partiria o link para essa page? fiquei com essa dúvida. Posso pegar essa issue ?

Como assim "de onde partiria o link"?
Você pode pegar essa issue sim.

Você pode entrar na nossa comunidade no discord para eventuais dúvidas durante a produção da página.

**Comment by matheusdoedev** [comment]
Falo o botão/link que vai levar a página

**Comment by IncognitaDev** [comment]
Ah sim, como a parte de login ainda não está pronta, inicialmente fica só a página mesmo, não é nescessário fazer um botão que leve até ela. Isso será resolvido depois.

**Comment by matheusdoedev** [comment]
Ok

**Comment by IncognitaDev** [comment]
> Falo o botão/link que vai levar a página. Beleza!

Ira fazer essa issue?

**Comment by matheusdoedev** [comment]
Vou sim, estou fazendo a tela aqui

**Comment by arthrc** [comment]
o gurizada, achei daora a ideia e tal mas ela vai ser tornar repetititva? Pois vai chegar um momento onde o raking vai ser composto somente de pessoas que fizeram todos os desafios
