### ISSUE TITLE
Filtrar por categorias

### ISSUE THREAD

**Issue by elmjunior** [Lorenalgm/DevChallenge#7]
Olá, estava analisando o código fonte para fazer algumas contribuições e notei que atualmente não está implementado nenhuma funcionalidade referente a filtragem por categorias.

Posso ajudar a implementar esta funcionalidade, assim como melhorar um pouco a estrutura de componentização do projeto, criando novos componentes independentes e separando um pouco as responsabilidades de cada componente.

Pra a questão da filtragem por categorias, gostaria de saber como está estruturado o backend e se temos algum endpoint de listagem de categorias, assim como a listagem de desafios filtrados por categorias.

Espero por contribuir no que for preciso.

**Comment by mmouradev** [comment]
Olá, ainda não está implementada nenhuma funcionalidade de filtro.
Pode dar uma olhada na API pelo repositório: [DevChallengeAPI](https://github.com/Lorenalgm/DevChallengeAPI)
Valeu!

**Comment by Lorenalgm** [comment]
Oi, Edilson!

Seria massa se puder implementar essa funcionalidade, ela ainda não existe mesmo, como o Matheus comentou!

Se tiver alguma dúvida no repositório fico à disposição :)

E valeu pela ajuda desde já!

**Comment by predrinn** [comment]
Olá! Eu posso ajudar na parte de filtragem, fiz um PR no back-end recentemente e espero que possa contribuir dando uns retoques no servidor.

**Comment by elmjunior** [comment]
Ja fiz as alterações no front-end no fork que criei hoje pela manhã.

Vou realizar os ajustes com as alterações que o @predrinn fez no backend para consultar os endpoints corretamente

**Comment by Lorenalgm** [comment]
Show, pessoal! As alterações que enviaram já estão em produção :)

**Comment by Hilverton** [comment]
Bom dia!

Então, estou com o filtro por categorias pronto no front, só que fiz uns ajustes e pretendo fazer outros para melhorar o site.

1. O submit da newsletter está aceitando entrada vazia, resolvi de forma temporária.
2. O componente de notificação da newsletter está com erro, mas ainda não resolvi.
3. Filtro por categoria.
4. Sugestão de deixar o botão da newsletter com o mesmo tamanho do respectivo form e com o mesmo valor do border-radius (acho que faz mas sentido).

Devo mandar essas alterações em uma única pull request ou em pull requests diferentes?

**Comment by magdielndantas** [comment]
> Bom dia!
> 
> Então, estou com o filtro por categorias pronto no front, só que fiz uns ajustes e pretendo fazer outros para melhorar o site.
> 
> 1. O submit da newsletter está aceitando entrada vazia, resolvi de forma temporária.
> 2. O componente de notificação da newsletter está com erro, mas ainda não resolvi.
> 3. Filtro por categoria. (Resolvido)
> 4. Sugestão de deixar o botão da newsletter com o mesmo tamanho do respectivo form e com o mesmo valor do border-radius (acho que faz mas sentido).
> 
> Devo mandar essas alterações em uma única pull request ou em pull requests diferentes?

Em relação ao botão da newsletter, creio que o interessante seria aplicar as mudanças de tamanho e borda no form, já que outros elementos do site seguem um esquema de estilo parecido

**Comment by Hilverton** [comment]
Beleza! Vou fazer o seguinte, vou mandar a pull request com a funcionalidade do filtro. Preferem que eu abra outra Jesus pra falar sobre as mudanças do layout ou continuo por aqui?

**Comment by mmouradev** [comment]
Olá @Hilverton, peço que faça a PR apenas com os itens relacionados ao filtro e que abra issues para discutir os outros detalhes que pretende modificar, obrigado pelo apoio!

**Comment by Lorenalgm** [comment]
Show! Funcionalidade já em produção!
